export {default as Preloader} from './Preloader/Preloader'
export {default as ErrorPage} from './ErrorPage/ErrorPage'
export {default as MyButton} from './MyButton/MyButton'
export {default as InformationPair} from './InformationPair/InformationPair'
export {default as Mock} from './Mock/Mock'