export {default as ProfilePageContainer} from './ProfilePage/ProfilePageContainer'
export {default as UserInfo} from './UserInfo/UserInfo'
export {default as UserStatusContainer} from './UserStatus/UserStatusContainer'
export {default as NewPostContainer} from './NewPost/NewPostContainer'
export {default as UserPostsContainer} from './UserPosts/UserPostsContainer'
export {default as UserPost} from './UserPost/UserPost'
export {default as UserPosts} from './UserPosts/UserPosts'