export type {default as GetUsersRequest} from './Users/GetUsersRequest'
export type {default as SetStatusRequest} from './Users/SetStatusRequest'
export type {default as EditProfileRequest} from './Users/EditProfileRequest'
export type {default as AddPostRequest} from './Posts/AddPostRequest'
export type {default as AddMessageRequest} from './Messages/AddMessageRequest'
export type {default as RegisterRequest} from './Auth/RegisterRequest'
export type {default as LoginRequest} from './Auth/LoginRequest'